name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  tests:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode 13.4.1
        run: sudo xcode-select -s /Applications/Xcode_13.4.1.app
      - name: Run tests
        run: make test
