name: Format
on:
  push:
    branches:
      - main
jobs:
  format:
    name: swift-format
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode 13.4.1
        run: sudo xcode-select -s /Applications/Xcode_13.4.1.app
      - name: Tap
        run: brew tap pointfreeco/formulae
      - name: Install
        run: brew install Formulae/swift-format@5.6
      - name: Format
        run: make format
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Run swift format
          branch: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
